# ZSH Configuration

# clear
# zmodload zsh/zprof
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="powerlevel10k/powerlevel10k"
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
[ "$TERM" = "xterm-kitty" ] && alias ssh="kitty +kitten ssh"
zstyle ':omz:plugins:nvm' lazy yes

plugins=(git
	zsh-syntax-highlighting
	zsh-autosuggestions
	sudo
	extract
	autojump
	nvm
	)

source $ZSH/oh-my-zsh.sh

[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
[[ ! -f ~/.dotfile/shell/p10k.zsh ]] || source ~/.dotfile/shell/p10k.zsh

######################
## Mac Config       ##
######################

# brew
eval "$(/opt/homebrew/bin/brew shellenv)"

# nvm 会拖慢启动速度
# export NVM_DIR="$HOME/.nvm"
# [ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"                                       # This loads nvm
# [ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" # This loads nvm bash_completion
export PATH="./node_modules/.bin:$PATH"

# pnpm
export PNPM_HOME="/Users/bytedance/Library/pnpm"
case ":$PATH:" in
*":$PNPM_HOME:"*) ;;
*) export PATH="$PNPM_HOME:$PATH" ;;
esac

# bun
export PATH="~/.bun/bin:$PATH"

# others
source ~/.dotfile/shell/shortcut.sh
export OPENCV_LOG_LEVEL=ERROR
eval $(thefuck --alias)
source <(fzf --zsh)

# source /opt/ros/iron/setup.zsh

/opt/homebrew/bin/im-select com.apple.keylayout.ABC

export PATH="/opt/homebrew/opt/ruby/bin:$PATH"
source /opt/homebrew/opt/chruby/share/chruby/chruby.sh
source /opt/homebrew/opt/chruby/share/chruby/chruby.sh
source /opt/homebrew/opt/chruby/share/chruby/auto.sh
chruby ruby-3.3.5

# bun completions
[ -s "/Users/bytedance/.bun/_bun" ] && source "/Users/bytedance/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

autoload -Uz compinit && compinit
export PATH="/opt/homebrew/opt/openjdk@17/bin:$PATH"
export ANDROID_HOME=/Users/bytedance/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools

# PDM
export PATH="~/Public/PDM:$PATH"

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/bytedance/.miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/bytedance/.miniconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/bytedance/.miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/bytedance/.miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

export PATH="/opt/homebrew/opt/binutils/bin:$PATH"
  export LDFLAGS="-L/opt/homebrew/opt/binutils/lib"
  export CPPFLAGS="-I/opt/homebrew/opt/binutils/include"

# pnpm
export PNPM_HOME="/Users/bytedance/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

# Added by coco installer
export PATH="/Users/bytedance/.local/bin:$PATH"
