[Basic]
# 跟随光标
FollowCaret=False
# 主题
Theme=System
# 默认主题
DefaultTheme=System

[LightMode]
# 覆盖默认值
OverrideDefault=False
# 高亮颜色
HighlightColor=#0000ff
# 悬停时高亮颜色
HighlightHoverColor=#00007f
# 高亮文本颜色
HighlightTextColor=#ffffff
# 按下时高亮文本颜色
HighlightTextPressColor=#7f7f7f
# 高亮标签颜色
HighlightLabelColor=#ffffff
# 高亮注释颜色
HighlightCommentColor=#ffffff
# 高亮标记颜色
HighlightMarkColor=#ffffff
# 面板颜色
PanelColor=#ffffff
# 文本颜色
TextColor=#000000
# 标签颜色
LabelColor=#000000
# 注释颜色
CommentColor=#000000
# 翻页按钮颜色
PagingButtonColor=#000000
# 禁用的翻页按钮颜色
DisabledPagingButtonColor=#7f7f7f
# 指示文本颜色
AuxColor=#000000
# 光标前的预编辑颜色
PreeditColorPreCaret=#000000
# 预编辑光标颜色
PreeditColorCaret=#000000
# 光标后的预编辑颜色
PreeditColorPostCaret=#000000
# 边框颜色
BorderColor=#000000
# 分隔线颜色
DividerColor=#000000

[DarkMode]
# 覆盖默认值
OverrideDefault=False
# 与浅色模式相同
SameWithLightMode=False
# 高亮颜色
HighlightColor=#0000ff
# 悬停时高亮颜色
HighlightHoverColor=#00007f
# 高亮文本颜色
HighlightTextColor=#ffffff
# 按下时高亮文本颜色
HighlightTextPressColor=#7f7f7f
# 高亮标签颜色
HighlightLabelColor=#ffffff
# 高亮注释颜色
HighlightCommentColor=#ffffff
# 高亮标记颜色
HighlightMarkColor=#ffffff
# 面板颜色
PanelColor=#000000
# 文本颜色
TextColor=#ffffff
# 标签颜色
LabelColor=#ffffff
# 注释颜色
CommentColor=#ffffff
# 翻页按钮颜色
PagingButtonColor=#ffffff
# 禁用的翻页按钮颜色
DisabledPagingButtonColor=#7f7f7f
# 指示文本颜色
AuxColor=#ffffff
# 光标前的预编辑颜色
PreeditColorPreCaret=#ffffff
# 预编辑光标颜色
PreeditColorCaret=#ffffff
# 光标后的预编辑颜色
PreeditColorPostCaret=#ffffff
# 边框颜色
BorderColor=#ffffff
# 分隔线颜色
DividerColor=#ffffff

[Typography]
# 布局
Layout=Horizontal
# 书写模式
WritingMode="Horizontal top-bottom"
# 输入法感知版式
TypographyAwarenessForIM=True
# 垂直时注释右对齐
VerticalCommentsAlignRight=False
# 翻页按钮样式
PagingButtonsStyle=Arrow

[ScrollMode]
# 启用卷轴
EnableScroll=True
# 自动展开
AutoExpand=False
# 显示滚动条
ShowScrollBar=True
# 动画
Animation=True
# 最大行数
MaxRowCount=5
# 最大列数
MaxColumnCount=7
# 选词
SelectCandidate=
# 用主键盘数字键选词
UseMainKeyboardNumberKeys=True
# 用小键盘数字键选词
UseKeypadNumberKeys=False
# 针对 Hyper 键优化
OptimizeForHyperKey=True

[ScrollMode/Expand]
0=equal
1=Down

[ScrollMode/Collapse]
0=minus

[ScrollMode/Up]
0=minus
1=Up

[ScrollMode/Down]
0=equal
1=Down

[ScrollMode/Left]
0=Left

[ScrollMode/Right]
0=Right

[ScrollMode/RowStart]
0=Home

[ScrollMode/RowEnd]
0=End

[ScrollMode/PageUp]
0=Page_Up

[ScrollMode/PageDown]
0=Next

[ScrollMode/Commit]
0=space

[Background]
# 图片
ImageUrl=
# 有图片时保留面板颜色
KeepPanelColorWhenHasImage=False
# 模糊
Blur="Liquid Glass"
# 阴影
Shadow=True

[Font]
# 文本字号
TextFontSize=16
# 文本字重
TextFontWeight=400
# 标签字号
LabelFontSize=12
# 标签字重
LabelFontWeight=400
# 注释字号
CommentFontSize=12
# 注释字重
CommentFontWeight=400
# 预编辑字号
PreeditFontSize=16
# 预编辑字重
PreeditFontWeight=400

[Font/TextFontFamily]
0="LXGW WenKai Screen"

[Font/LabelFontFamily]
0=

[Font/CommentFontFamily]
0=

[Font/PreeditFontFamily]
0=

[Caret]
# 样式
Style=Blink
# 文本
Text=‸

[Highlight]
# 标记样式
MarkStyle=None
# 标记文本
MarkText=🐧
# 悬停行为
HoverBehavior=None

[Size]
# 覆盖默认值
OverrideDefault=False
# 边框宽度（px）
BorderWidth=1
# 边框半径（px）
BorderRadius=6
# 外边距（px）
Margin=0
# 高亮半径（px）
HighlightRadius=0
# 顶填充（px）
TopPadding=3
# 右填充（px）
RightPadding=7
# 底填充（px）
BottomPadding=3
# 左填充（px）
LeftPadding=7
# 标签、文本、注释间隔（px）
LabelTextGap=6
# 垂直时最小宽度（px）
VerticalMinWidth=200
# 卷轴单元格宽度 (px)
ScrollCellWidth=65
# 水平分隔线宽度（px）
HorizontalDividerWidth=1

[Advanced]
# 用户 CSS
UserCss=
# 复制 HTML
CopyHtml=
# 我知道使用插件可能有风险
PluginNotice=False
# 插件
Plugins=

[Advanced/UnsafeAPI]
# curl
EnableUnsafeCurlAPI=False

